export type MinerKey = "gram" | "usdt";

/**
 * A Music NFT: a real, freely licensed song (CC-BY 3.0, Josh Woodward) that
 * doubles as a mining rig. Yields are per day and intentionally realistic —
 * they are quoted against the live market value of GRAM and USDT.
 */
export type NftDef = {
  id: string;
  name: string; // song title
  artist: string;
  album: string;
  license: string;
  audioUrl: string;
  coverUrl: string;
  desc: string;
  /** Daily production of each coin while the NFT is in your collection. */
  musicPerDay: number;
  gramPerDay: number;
  usdtPerDay: number;
  unlocks: MinerKey[];
  stars: number; // Telegram Stars price (0 = not for sale)
  gram: number; // GRAM price (0 = not for sale)
  tone: string; // gradient for the disc label
  rarity: "Free" | "Common" | "Rare" | "Epic" | "Legendary";
  /** Reward-only records are never listed in the shop. */
  reward?: "welcome" | "referral";
};

const A = {
  crawford: "Crawford_Street-17897",
  machine: "The_Beautiful_Machine-16742",
  ashes: "Ashes-15242",
  wake: "The_Wake_1790-15241",
} as const;

const audio = (item: string, file: string) => `https://archive.org/download/${item}/${file}`;
const cover = (item: string) => `https://archive.org/services/img/${item}`;

const TONES = [
  "from-sky-400/50 to-cyan-500/10",
  "from-amber-300/50 to-orange-600/10",
  "from-fuchsia-400/50 to-violet-600/10",
  "from-emerald-300/50 to-teal-600/10",
  "from-rose-400/50 to-pink-600/10",
  "from-indigo-400/50 to-blue-700/10",
];

export const NFTS: NftDef[] = [
  {
    id: "welcome-nft",
    name: "Little Tomcat",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_17_-_Little_Tomcat.mp3"),
    coverUrl: cover(A.wake),
    desc: "Your free welcome record. Mines MUSIC from day one.",
    musicPerDay: 1260,
    gramPerDay: 0.0,
    usdtPerDay: 0.0,
    unlocks: [],
    stars: 0,
    gram: 0,
    tone: TONES[0]!,
    rarity: "Free",
    reward: "welcome",
  },
  {
    id: "friends-nft",
    name: "The Dreamers",
    artist: "Josh Woodward",
    album: "The Beautiful Machine",
    license: "CC BY 3.0",
    audioUrl: audio(A.machine, "Josh_Woodward_-_25_-_The_Dreamers.mp3"),
    coverUrl: cover(A.machine),
    desc: "Free when 5 friends join. Switches GRAM and USDT mining on forever.",
    musicPerDay: 3360,
    gramPerDay: 0.0252,
    usdtPerDay: 0.0756,
    unlocks: ["gram", "usdt"],
    stars: 0,
    gram: 0,
    tone: TONES[1]!,
    rarity: "Rare",
    reward: "referral",
  },

  /* ---------- Common ---------- */
  {
    id: "swansong",
    name: "Let It In",
    artist: "Josh Woodward",
    album: "Ashes",
    license: "CC BY 3.0",
    audioUrl: audio(A.ashes, "Josh_Woodward_-_01_-_Let_It_In.mp3"),
    coverUrl: cover(A.ashes),
    desc: "Entry record. Turns on GRAM mining.",
    musicPerDay: 2721.6,
    gramPerDay: 0.040824,
    usdtPerDay: 0.13608,
    unlocks: ["gram"],
    stars: 270,
    gram: 1.5,
    tone: TONES[0]!,
    rarity: "Common",
  },
  {
    id: "cherry",
    name: "Cherry",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_03_-_Cherry.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Bright pop cut with a steady GRAM stream.",
    musicPerDay: 3326.4,
    gramPerDay: 0.061236,
    usdtPerDay: 0.176904,
    unlocks: ["gram"],
    stars: 540,
    gram: 3,
    tone: TONES[4]!,
    rarity: "Common",
  },
  {
    id: "fight-the-sea",
    name: "Fight the Sea",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_01_-_Fight_the_Sea.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Warm indie rock. Adds USDT on top of GRAM.",
    musicPerDay: 3931.2,
    gramPerDay: 0.074844,
    usdtPerDay: 0.224532,
    unlocks: ["gram", "usdt"],
    stars: 1080,
    gram: 6,
    tone: TONES[3]!,
    rarity: "Common",
  },
  {
    id: "under-the-stairs",
    name: "California Lullabye",
    artist: "Josh Woodward",
    album: "The Beautiful Machine",
    license: "CC BY 3.0",
    audioUrl: audio(A.machine, "Josh_Woodward_-_01_-_California_Lullabye.mp3"),
    coverUrl: cover(A.machine),
    desc: "Quiet grower with a dependable daily payout.",
    musicPerDay: 4838.4,
    gramPerDay: 0.095256,
    usdtPerDay: 0.278964,
    unlocks: ["gram", "usdt"],
    stars: 1620,
    gram: 9,
    tone: TONES[5]!,
    rarity: "Common",
  },

  /* ---------- Rare ---------- */
  {
    id: "border-blaster",
    name: "Shot Down",
    artist: "Josh Woodward",
    album: "The Beautiful Machine",
    license: "CC BY 3.0",
    audioUrl: audio(A.machine, "Josh_Woodward_-_03_-_Shot_Down.mp3"),
    coverUrl: cover(A.machine),
    desc: "Rare pressing. Roughly double a Common record.",
    musicPerDay: 7526.4,
    gramPerDay: 0.155232,
    usdtPerDay: 0.45864,
    unlocks: ["gram", "usdt"],
    stars: 2160,
    gram: 12,
    tone: TONES[1]!,
    rarity: "Rare",
  },
  {
    id: "big-disco-ball",
    name: "Big Disco Ball",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_07_-_Big_Disco_Ball.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Dancefloor rare with a strong USDT stream.",
    musicPerDay: 8780.8,
    gramPerDay: 0.183456,
    usdtPerDay: 0.550368,
    unlocks: ["gram", "usdt"],
    stars: 2880,
    gram: 16,
    tone: TONES[4]!,
    rarity: "Rare",
  },
  {
    id: "grey-snow",
    name: "Cherubs",
    artist: "Josh Woodward",
    album: "Ashes",
    license: "CC BY 3.0",
    audioUrl: audio(A.ashes, "Josh_Woodward_-_02_-_Cherubs.mp3"),
    coverUrl: cover(A.ashes),
    desc: "Slow burner, heavy on stablecoin output.",
    musicPerDay: 10035.2,
    gramPerDay: 0.218736,
    usdtPerDay: 0.649152,
    unlocks: ["gram", "usdt"],
    stars: 3780,
    gram: 21,
    tone: TONES[5]!,
    rarity: "Rare",
  },
  {
    id: "invisible-light",
    name: "Invisible Light",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_13_-_Invisible_Light.mp3"),
    coverUrl: cover(A.wake),
    desc: "Rare record with balanced GRAM and USDT yields.",
    musicPerDay: 11603.2,
    gramPerDay: 0.261072,
    usdtPerDay: 0.77616,
    unlocks: ["gram", "usdt"],
    stars: 4860,
    gram: 27,
    tone: TONES[0]!,
    rarity: "Rare",
  },

  /* ---------- Epic ---------- */
  {
    id: "private-hurricane",
    name: "Faded War",
    artist: "Josh Woodward",
    album: "The Beautiful Machine",
    license: "CC BY 3.0",
    audioUrl: audio(A.machine, "Josh_Woodward_-_05_-_Faded_War.mp3"),
    coverUrl: cover(A.machine),
    desc: "Epic pressing. A serious daily crypto stream.",
    musicPerDay: 17864,
    gramPerDay: 0.40194,
    usdtPerDay: 1.20582,
    unlocks: ["gram", "usdt"],
    stars: 6120,
    gram: 34,
    tone: TONES[2]!,
    rarity: "Epic",
  },
  {
    id: "stars-collide",
    name: "Infinite Horizon",
    artist: "Josh Woodward",
    album: "Ashes",
    license: "CC BY 3.0",
    audioUrl: audio(A.ashes, "Josh_Woodward_-_03_-_Infinite_Horizon.mp3"),
    coverUrl: cover(A.ashes),
    desc: "Epic anthem with an outsized USDT payout.",
    musicPerDay: 21924,
    gramPerDay: 0.496944,
    usdtPerDay: 1.4616,
    unlocks: ["gram", "usdt"],
    stars: 7560,
    gram: 42,
    tone: TONES[3]!,
    rarity: "Epic",
  },
  {
    id: "the-spirit-world",
    name: "The Spirit World",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_11_-_The_Spirit_World.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Dark epic. Big on GRAM, bigger on USDT.",
    musicPerDay: 25984,
    gramPerDay: 0.591948,
    usdtPerDay: 1.75392,
    unlocks: ["gram", "usdt"],
    stars: 9360,
    gram: 52,
    tone: TONES[5]!,
    rarity: "Epic",
  },
  {
    id: "golden-sunrise",
    name: "Golden Sunrise",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_19_-_Golden_Sunrise.mp3"),
    coverUrl: cover(A.wake),
    desc: "The brightest epic in the collection.",
    musicPerDay: 30856,
    gramPerDay: 0.701568,
    usdtPerDay: 2.08278,
    unlocks: ["gram", "usdt"],
    stars: 11520,
    gram: 64,
    tone: TONES[1]!,
    rarity: "Epic",
  },

  /* ---------- Legendary ---------- */
  {
    id: "overthrown",
    name: "Memory Replaced",
    artist: "Josh Woodward",
    album: "The Beautiful Machine",
    license: "CC BY 3.0",
    audioUrl: audio(A.machine, "Josh_Woodward_-_11_-_Memory_Replaced.mp3"),
    coverUrl: cover(A.machine),
    desc: "Legendary master. Top-tier crypto yield.",
    musicPerDay: 43680,
    gramPerDay: 0.9828,
    usdtPerDay: 2.9484,
    unlocks: ["gram", "usdt"],
    stars: 14040,
    gram: 78,
    tone: TONES[2]!,
    rarity: "Legendary",
  },
  {
    id: "gemini",
    name: "Gemini",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_23_-_Gemini.mp3"),
    coverUrl: cover(A.wake),
    desc: "Legendary twin-coin master press.",
    musicPerDay: 52080,
    gramPerDay: 1.1718,
    usdtPerDay: 3.4776,
    unlocks: ["gram", "usdt"],
    stars: 17100,
    gram: 95,
    tone: TONES[0]!,
    rarity: "Legendary",
  },
  {
    id: "2020",
    name: "Branches",
    artist: "Josh Woodward",
    album: "The Beautiful Machine",
    license: "CC BY 3.0",
    audioUrl: audio(A.machine, "Josh_Woodward_-_23_-_Branches.mp3"),
    coverUrl: cover(A.machine),
    desc: "The rarest record in the vault.",
    musicPerDay: 63840,
    gramPerDay: 1.4364,
    usdtPerDay: 4.2336,
    unlocks: ["gram", "usdt"],
    stars: 20700,
    gram: 115,
    tone: TONES[4]!,
    rarity: "Legendary",
  },
];

export function nftById(id: string) {
  return NFTS.find((n) => n.id === id) ?? null;
}

/** NFTs the user can actually buy. */
export const SHOP_NFTS = NFTS.filter((n) => !n.reward);
